import { BadRequestException } from '@nestjs/common'

export enum ServerMessage {
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  INVALID_PERMISSION = 'INVALID_PERMISSION',
  INVALID_ROLE = 'INVALID_ROLE',

  FILE_NOT_FOUND = 'FILE_NOT_FOUND',

  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_WAS_EXISTED = 'TEMPLATE_WAS_EXISTED',
  TEMPLATE_WAS_DELETED = 'TEMPLATE_WAS_DELETED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_WAS_EXISTED = 'USER_WAS_EXISTED',
  USER_WAS_DELETED = 'USER_WAS_DELETED',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  USER_HAS_PASSWORD = 'USER_HAS_PASSWORD',
  NEW_PASSWORD_BE_OLD_PASSWORD = 'NEW_PASSWORD_BE_OLD_PASSWORD',

  ADVERTISEMENT_NOT_FOUND = 'ADVERTISEMENT_NOT_FOUND',
  ADVERTISEMENT_WAS_EXISTED = 'ADVERTISEMENT_WAS_EXISTED',
  ADVERTISEMENT_WAS_DELETED = 'ADVERTISEMENT_WAS_DELETED',

  POST_CATEGORY_NOT_FOUND = 'POST_CATEGORY_NOT_FOUND',
  POST_CATEGORY_WAS_EXISTED = 'POST_CATEGORY_WAS_EXISTED',
  POST_CATEGORY_NAME_OR_SLUG_WAS_EXISTED = 'POST_CATEGORY_NAME_OR_SLUG_WAS_EXISTED',
  POST_CATEGORY_WAS_DELETED = 'POST_CATEGORY_WAS_DELETED',

  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_WAS_EXISTED = 'POST_WAS_EXISTED',
  POST_TITLE_OR_SLUG_WAS_EXISTED = 'POST_TITLE_OR_SLUG_WAS_EXISTED',
  POST_WAS_DELETED = 'POST_WAS_DELETED',

  AUTHOR_NOT_FOUND = 'AUTHOR_NOT_FOUND',
  AUTHOR_WAS_EXISTED = 'AUTHOR_WAS_EXISTED',
  AUTHOR_WAS_DELETED = 'AUTHOR_WAS_DELETED',

  CATEGORY_BOOK_NOT_FOUND = 'CATEGORY_BOOK_NOT_FOUND',
  CATEGORY_BOOK_WAS_EXISTED = 'CATEGORY_BOOK_WAS_EXISTED',
  CATEGORY_BOOK_WAS_DELETED = 'CATEGORY_BOOK_WAS_DELETED',

  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  BOOK_WAS_EXISTED = 'BOOK_WAS_EXISTED',
  BOOK_WAS_DELETED = 'BOOK_WAS_DELETED',

  WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND',
  WAREHOUSE_WAS_EXISTED = 'WAREHOUSE_WAS_EXISTED',
  WAREHOUSE_WAS_DELETED = 'WAREHOUSE_WAS_DELETED',
}
